=== ugopen/nxopen_lib/NX12.0.2.9/UGOPEN/SampleNXOpenApplications/.NET/CAMSetupImport/SimulationApi.xsd
<?xml version="1.0" encoding="utf-8"?>
<!--==============================================================================
 
        Copyright (c) 2017 Siemens Product Lifecycle Management Software Inc.
                         Unpublished - All rights reserved

==============================================================================

 Description
    This file contains classes to import geometry files into the workpart


==============================================================================-->
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Resources">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Machine">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Name" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="ProgramList">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="Program" type="Program"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Parts">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="Part">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Name" type="xs:string" />
                                        <xs:element minOccurs="0" name="IsFinishedPart" type="xs:boolean" />
                                        <xs:element name="Path" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Clamps">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="Clamp">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Name" type="xs:string" />
                                        <xs:element minOccurs="0" name="Path" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Instances">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Clamps">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="unbounded" name="Clamp" type="Instance"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Parts">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="unbounded" name="Part" type="Instance"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="ToolList">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="CarrierPlacements">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="unbounded" name="Carrier">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Name" type="xs:string" />
                                                    <xs:element maxOccurs="unbounded" name="Slot">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="Name" type="xs:string" />
                                                                <xs:element name="Tool" type="xs:string" />
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="Program">
        <xs:sequence>
            <xs:element name="PrgID" type="xs:string" />
            <xs:element name="FileName" type="xs:string" />
            <xs:element minOccurs="0" name="Channel" type="xs:string" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Position">
        <xs:sequence>
            <xs:element name="X" type="xs:decimal" />
            <xs:element name="Y" type="xs:decimal" />
            <xs:element name="Z" type="xs:decimal" />
            <xs:element name="Alpha" type="xs:decimal" />
            <xs:element name="Beta" type="xs:decimal" />
            <xs:element name="Gamma" type="xs:decimal" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Instance">
        <xs:sequence>
            <xs:element name="Name" type="xs:string" />
            <xs:element name="ID" type="xs:string" />
            <xs:element name="Position" type="Position"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== ugopen/nxopen_lib/NX1953_NX1957_NX1961_NX1965_NX1969_NX1973/UGOPEN/SampleNXOpenApplications/.NET/CAMSetupImport/sample/sim01.XML
<?xml version="1.0" encoding="utf-8"?>
<!--
==============================================================================
 
        Copyright (c) 2017 Siemens Product Lifecycle Management Software Inc.
                         Unpublished - All rights reserved

==============================================================================

 Description
    This file contains an example for the cams setup import xml file to be used with the cam setup import.


==============================================================================
-->
<Resources xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\SimulationApi.xsd">
  <Machine>
    <Name>sim01_mill_3ax_sinumerik</Name>
  </Machine>
  <ProgramList>
    <Program>
      <PrgID>Main</PrgID>
      <FileName>sim01_mill_3ax_cam_sinumerik_mm.mpf</FileName>
      <Channel>Main</Channel>
    </Program>
    <Program>
      <PrgID>to_ini</PrgID>
      <FileName>to_ini.ini</FileName>
    </Program>
  </ProgramList>
  <Parts>
    <Part>
      <Name>part</Name>
      <IsFinishedPart>true</IsFinishedPart>
      <Path>library\parts\sim_final2.stp</Path>
    </Part>
    <Part>
      <Name>blank</Name>
      <IsFinishedPart>false</IsFinishedPart>
      <Path>library\parts\sim_blank2.prt</Path>
    </Part>
  </Parts>
  <Clamps>
    <Clamp>
      <Name>clamp1</Name>
      <Path>library\clamps\sim_fix_vise.prt</Path>
    </Clamp>
    <Clamp>
      <Name>clamp2</Name>
      <Path>library\clamps\sim_fix_visejaw.prt</Path>
    </Clamp>
  </Clamps>
  <Instances>
    <Clamps>
      <Clamp>
        <Name>clamp1</Name>
        <ID>CLAMP-1</ID>
        <Position>
          <X>0</X>
          <Y>0</Y>
          <Z>0</Z>
          <Alpha>1.570796</Alpha>
          <Beta>-0.000000</Beta>
          <Gamma>0.000000</Gamma>
        </Position>
      </Clamp>
      <Clamp>
        <Name>clamp2</Name>
        <ID>CLAMP-2</ID>
        <Position>
          <X>0</X>
          <Y>88.5</Y>
          <Z>0</Z>
          <Alpha>1.570796</Alpha>
          <Beta>-0.000000</Beta>
          <Gamma>0.000000</Gamma>
        </Position>
      </Clamp>
    </Clamps>
    <Parts>
      <Part>
        <Name>part</Name>
        <ID>PART</ID>
        <Position>
          <X>-50.8</X>
          <Y>-24.0252</Y>
          <Z>98.025</Z>
          <Alpha>0</Alpha>
          <Beta>-0.000000</Beta>
          <Gamma>0.000000</Gamma>
        </Position>
      </Part>
      <Part>
        <Name>blank</Name>
        <ID>BLANK</ID>
        <Position>
          <X>-51</X>
          <Y>-24.2252</Y>
          <Z>98.025</Z>
          <Alpha>0</Alpha>
          <Beta>-0.000000</Beta>
          <Gamma>0.000000</Gamma>
        </Position>
      </Part>
    </Parts>
  </Instances>
  <ToolList>
    <CarrierPlacements>
      <Carrier>
        <Name>TOOL_MAGAZINE</Name>
        <Slot>
          <Name>POCKET_01</Name>
          <Tool>ugti0202_030</Tool>
        </Slot>
        <Slot>
          <Name>POCKET_02</Name>
          <Tool>ugti0202_025</Tool>
        </Slot>
        <Slot>
          <Name>POCKET_03</Name>
          <Tool>ugti0201_062</Tool>
        </Slot>
      </Carrier>
    </CarrierPlacements>
  </ToolList>
</Resources>
